language: java
dist: trusty
sudo: required
before_install:
- |
  if [ "$SLACK_WEBHOOK_URL" != "" ]; then
    curl -X POST --data-urlencode "payload={ \"text\": \"About to install.\"}" ${SLACK_WEBHOOK_URL}
  fi
install:
- sudo apt-get install google-chrome-stable
- wget -N https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/bin/
- sudo chmod +x /usr/local/bin/chromedriver
addons:
  chrome: stable
jdk:
- oraclejdk11
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- |
  if [ "$SLACK_WEBHOOK_URL" != "" ]; then
    curl -X POST --data-urlencode "payload={ \"text\": \"About to build and run the scraper.\"}" ${SLACK_WEBHOOK_URL}
  fi
- cd shaungc-java-dev && mvn exec:java
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  slack:
    rooms:
      secure: Sjp4VVuZ3wtJQTOcOnXJFZn93VRXUjJ+xnm/M9LsnAHrZag6bGn1+YTYUDhQ4zG13B5sJ0X6uES7Z67mrDHztky2439369iJHtGUjGXHNUW1DUsMcBqiUvuurzZ64CpDmqAObOna65hvEH9FZIeANV3vqNHzGajWjCyaU2GBMr0NXXI8UcJo6wUWs4P6YIya4agbqrE9PjOuuCJjt26dgQ347RoUpYZoVd5bhhYvm727/PgoEfYWqJUBY1OV9H2U8PnK0o4dZOq4YsZI+7ynDLAdkG0UdYa00PC8xo4+RbMCHWoAkHkiVaez6KdzEV5h6kAJ72pNHHYKgixENWYdeE21WGSszJdi6G4N+mHVm2hZBjl1GikPBJou4wzfXrhl1CZ2GDKUHOovGjcMjMYYVOiBjIyES8pLssVaOeXhpXlS/HJYbO+03CebXLtW7QFgXpaSndP2KFwDbZQnnuhJqzewHkc9W8MUqxfkPzURvtvK1zM+EGd7QDy2q3PCzdl5or134K0xv/TWluzr4PB2jzjyfsJzUaKQsdgUoCKOTlZxKw4Iwv5eAQ/Abg1YUcAULQQvs9GfBBSIUSaNr2tICLQvrK/t3TL/teeleiGzcUl9TlY1MQTjXbumBu8+/a8KZEvPVMo6WlhMPDaBs3CyhsBWrDcAsq/T0x14rcJnA+Q=
    on_start: always
    on_success: always
    on_failure: always
    template:
    - "*%{repository_slug}: %{message}*"
    - "*Git commit:* %{commit_message}"
    - 'Build result: %{result} in %{duration}'
    - 'Commit hash: `%{commit}`'
    - 'Build details: %{build_url}'
